[project]
name = "fastapi-backend"
version = "0.1.0"
description = "fastapi-backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "starlette",
    "pydantic",
    "annotated-types",
    "anyio",
    "httpx",
    "h11",
    "httpcore",
    "idna",
    "SQLAlchemy",
    "aiomysql",
    "PyMySQL",
    "numpy",
    "pandas",
    "celery",
    "APScheduler",
    "amqp",
    "kombu",
    "billiard",
    "vine",
    "celery-types",
    "redis",
    "loguru",
    "PyJWT",
    "bcrypt",
    "python-dotenv",
    "shortuuid",
    "snowflake-id",
    "openai",
    "orjson",
    "tqdm",
    "jiter",
    "protobuf",
    "grpcio",
    "grpcio-tools",
    "certifi",
    "click",
    "packaging",
    "python-dateutil",
    "pytz",
    "tzdata",
    "tzlocal",
    "typing-extensions",
    "typing-inspection",
    "requests"
]